version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: package-service-app
    working_dir: /usr/app
    env_file:
      - .env
    volumes:
      - ./:/usr/app
    command: air
    ports:
    - "${FORWARD_PORT:-8000}:${PORT:-8000}"
  db:
    image: mysql
    container_name: package-service-db
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:-package_service}"
      MYSQL_USER: "${DB_USERNAME:-user}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-user}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-root}"
    volumes:
      - "./.docker/mysql:/var/lib/mysql"
    command:
      - "--default-authentication-plugin=mysql_native_password"