version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: package-service-app
    working_dir: /usr/app
    env_file:
      - .env
    volumes:
      - ./:/usr/app
    command: air
    links:
      - db
    ports:
    - "${FORWARD_PORT:-8000}:${PORT:-8000}"
  db:
    image: mysql
    container_name: package-service-db
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:-package_service}"
      MYSQL_USER: "${DB_USERNAME:-user}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-user}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-root}"
    volumes:
      - "./.docker/mysql:/var/lib/mysql"
    command:
      - "--default-authentication-plugin=mysql_native_password"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./.docker/prometheus/:/etc/prometheus/
      - ./prometheus.yml/:/etc/prometheus/prometheus.yml
    links:
      - app
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    links:
      - prometheus
    volumes:
      - ./.docker/grafana/provisioning/:/etc/grafana/provisioning/